train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../trainingset/bubtub/x3_synthetic/
      repeat: 6
      first_k: 15
      last_k: 15
      cache: in_memory
  wrapper:
    name: sere-wrapper
    args:
      inp_size: 99
      volume_depth : 101
      sample_views: 13
      sample_centerview: null
      randomSeed: 0
      M: 63
      zspacing: 0.2*1e-6
      Nnum: 13
      scanning: 3
      rand_factor: 0.1
      RGN_noise: [0, 9] # expectation variance
  batch_size: 1

model:
  name: serenet
  args:
    inChannels : 49
    negative_slope: 0.1
    usingbias: True
    reset_param: True

optimizer:
  name: adam
  args:
    lr: 1.e-4

epoch_max: 800

loss_fn: 'utils.NLLMPGLoss(miu=0, var=9)'
epoch_save: 800

psf: ../psf/Ideal_PhazeSpacePSF_M63_NA1.4_zmin-10u_zmax10u_zspacing0.2u.mat
input_views: [84, 85, 98, 97, 96, 83, 70, 71, 72, 73, 86, 99, 112, 111, 110, 109, 108, 95, 82, 69, 56, 57, 58, 59, 60, 61, 74, 87, 100, 113, 125, 124, 123, 122, 121, 107, 94, 81, 68, 55, 43, 44, 45, 46, 47, 88, 136, 80, 32]
bpmode: selectiviews
shiftmode: psfcenterofmass