train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ../../../../trainingset/bubtub_Nnum13/x3_synthetic/
      root_path_2: ../../../../trainingset/bubtub_Nnum13/GT_synthetic/
      repeat: 6
      first_k: 15
      last_k: 15
      cache: in_memory
  wrapper:
    name: rlfm-vcdnet
    args:
      inp_size: 99
      volume_depth : 101
      randomSeed: 0
      Nnum: 13
      scanning: 3
  batch_size: 1

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ../../../../trainingset/bubtub_Nnum13/x3_synthetic/
      root_path_2: ../../../../trainingset/bubtub_Nnum13/GT_synthetic/
      repeat: 1
      first_k: 5
      last_k: 1
      cache: in_memory
  wrapper:
    name: rlfm-vcdnet
    args:
      inp_size: 99
      volume_depth : 101
      randomSeed: 0
      Nnum: 13
      scanning: 3
  batch_size: 1

model:
  name: hylfmnet
  args:
    inChannels : 169
    outChannels : 101

optimizer:
  name: adam
  args:
    lr: 1.e-4


loss_fn: 'torch.nn.MSELoss()'

epoch_val: 50
epoch_save: 50
epoch_max: 800
threshold: 0.5
epoch_threshold: 50
randfactor: 0