train_dataset:
  dataset:
    # name: paired-image-folders
    name: image-folder
    args:
      # tag: vessel
      root_path_1: ../../../../trainingset/bubtub_Nnum13/x3_synthetic/
      repeat: 6
      first_k: 15
      last_k: 15
      cache: in_memory
  wrapper:
    name: sere-wrapper
    args:
      inp_size: 99
      volume_depth : 101
      sample_views: 13
      sample_centerview: null
      randomSeed: 0
      M: 63
      zspacing: 0.2*1e-6
      Nnum: 13
      scanning: 3
      # RPN_noise: [30000,10000,3000,1000,300,100] 
      rand_factor: 0.1
      RGN_noise: [0, 9] # expectation variance
  batch_size: 1

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path_1: ../../../../trainingset/bubtub_Nnum13/x3_synthetic/
      repeat: 1
      first_k: 5
      last_k: 1
      cache: in_memory
  wrapper:
    name: sere-wrapper
    args:
      inp_size: 99
      volume_depth : 101
      sample_views: 2
      sample_centerview: True
      # angle_energy_norm: null
      randomSeed: 0
      M: 63
      zspacing: 0.2*1e-6
      Nnum: 13
      scanning: 3
      # RGN_noise: [0, 9] # expectation variance
      rand_factor: 1
  batch_size: 1



model:
  name: serenet
  args:
    inChannels : 49
    reset_param: True
    usingbias: True
    negative_slope: 0.1

optimizer:
  name: adam
  args:
    lr: 1.e-4

epoch_max: 800
# multi_step_lr:
#   milestones: [200, 400, 600, 800]
#   gamma: 0.5

loss_fns:
  pixel_loss1: 'utils.NLLMPGLoss(miu=0, var=9)'
  perceptual_loss: utils.LPIPS_vgg16_single_channel().cuda()
# LPIPS_vgg16_single_channel use torchvision's pretrained vgg16 model, I summed up the first convolutional weights manually to adapt to single channel input

epoch_val: 50
epoch_save: 50

psf: ../../../../psf/Ideal_PhazeSpacePSF_M63_NA1.4_zmin-10u_zmax10u_zspacing0.2u.mat
input_views: [84, 85, 98, 97, 96, 83, 70, 71, 72, 73, 86, 99, 112, 111, 110, 109, 108, 95, 82, 69, 56, 57, 58, 59, 60, 61, 74, 87, 100, 113, 125, 124, 123, 122, 121, 107, 94, 81, 68, 55, 43, 44, 45, 46, 47, 88, 136, 80, 32]
bpmode: selectiviews
shiftmode: psfcenterofmass